trigger: none
stages:
  - stage: 'Build'
    jobs:
    - job: RunTests
      pool:
        vmImage: ubuntu-20.04
        strategy:
          matrix:
            Python38:
              python.version: '3.8'
          maxParallel: 1
      steps:
      - script: |
          # store release tag and message
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          export GIT_TAG=`git describe`
          echo $GIT_TAG
          export TAG_MESSAGE=`git tag -n 0.2.0rc0 | awk '{$1=""; print}' | cut -c 2-`
          echo $TAG_MESSAGE

          git config --global user.name "CI Builder"
          git config --global user.email "monai.contact@gmail.com"

          root_dir=$(pwd)
          ohif_dir=${root_dir}/plugins/ohif
          
          pushd $ohif_dir
          ./build.sh
          popd

          pushd $ohif_dir/Viewers
          export YEAR_WEEK=$(date +'%y%U')
          git add .
          git commit -m "OHIF Update $YEAR_WEEK"

          git describe --tags --dirty --always --long
          popd

          git add .
          git commit -m "OHIF Update $YEAR_WEEK"
          git status

          # re-create the release tag from newly commited files from OHIF build
          git tag --delete $GIT_TAG
          git tag -a $GIT_TAG -m "${TAG_MESSAGE}"

        displayName: 'Build OHIF'
      - script: |
          python -m pip install --user --upgrade pip setuptools wheel twine
          python -m pip install torch>=1.5 torchvision
        displayName: 'Install dependencies'
      - script: |
          root_dir=$PWD
          echo "$root_dir"
          set -e

          # move packages to a temp dir
          export BUILD_OHIF=false
          python setup.py sdist bdist_wheel --build-number $(date +'%Y%m%d%H%M')
          tmp_dir=$(mktemp -d)
          cp dist/monailabel* "$tmp_dir"
          rm -r build monailabel.egg-info
          cd "$tmp_dir"
          ls -al

          # install from tar.gz
          python -m pip install monailabel*.tar.gz
          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
          python -c 'import monailabel; print(monailabel.__file__)'
          python -m pip uninstall -y monailabel
          rm monailabel*.tar.gz

          # install from wheel
          python -m pip install monailabel*.whl
          python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
          python -c 'import monailabel; print(monailabel.__file__)'
          python -m pip uninstall -y monailabel
          rm monailabel*.whl

          # install test utilities
          python -m pip install pytest

          # start the monailabel server in the background
          # and run the integration tests
          $root_dir/runtests.sh --net

          # cleanup
          cd "$root_dir"
          rm -r "$tmp_dir"
          rm -rf monailabel/
          ls -la .
        displayName: 'Build and test source archive and wheel file'
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: monailabel
          repositoryName: '$(Build.Repository.Name)'
          action: 'edit'
          # target: '$(tagName)'
          tagSource: 'manual'
          tag: 0.2.0
          addChangeLog: false 
          assets: '$(Build.ArtifactStagingDirectory)/*'
  